site_name: robodev
site_url: https://rosdoc/ # must have the trailing slash
nav:
  - Home: index.md
  - ROS2 For Beginners: ros.md
  - About: about.md
theme:
  name: readthedocs
  favicon: favicon.ico
