site_name: robodev
site_url: https://rosdoc/ # must have the trailing slash
nav:
  - Home: index.md
  - ROS2 For Beginners: ros.md
  - About: about.md
theme:
  name: readthedocs
  favicon: favicon.ico

markdown_extensions:
  - attr_list # allow to add HTML attributes and CSS classes
  - md_in_html # allow to write Markdown inside HTML elements

